services:
  - type: web
    name: telegram-autobazar-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bazar.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: MOD_GROUP_ID
        sync: false
